version: '3.8'
services:
  import_db:
    env_file: .env
    image: innovanon/import_db
    container_name:  import_db
    ports:
      - "0.0.0.0:65432:0.0.0.0:65432/tcp"
    volumes:
      - import-db:/var/teamhack/upload:rw
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #command: ["-S", "-U", $USER, "-P", $PASSWORD]
    #network_mode:    service:vpn-s1
    #healthcheck:
    #  test: ["CMD-SHELL", "nslookup hackthebox.com 0.0.0.0"]
    #  interval:     10s
    #  timeout:       3s
    #  retries:       10
    depends_on:
      msfrpcd:
        condition: service_healthy
      syslog:
        condition: service_started

volumes:
  import-db:

